### ISSUE TITLE
When I click Ok or Cancel it does not close itself

### ISSUE THREAD

**Issue by f3rnandomoreno** [mathieudutour/Meteor-popup-confirm#1]
I have created one popup but when I click on Ok or Cancel the popup throw an error:

`Exception in setTimeout callback: TypeError: undefined is not a function
    at http://localhost:3000/packages/matdutour_popup-confirm.js?ce9b06e625b4b966a2ce8f14f33e0dda1ce1e9b7:112:40
    at _.extend.withValue (http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:950:17)
    at http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:435:45
    at http://localhost:3000/packages/meteor.js?e53378596562e8922a6369c955bab1e047fa866b:978:22`

And it keeps visualized.

**Comment by f3rnandomoreno** [comment]
It is because in atmosphere readme you did not include the correct way. Github is:
has a `new` for creation the object.
It is not included in here: https://atmospherejs.com/matdutour/popup-confirm

**Comment by mathieudutour** [comment]
Oops sorry, i didn't publish the last version. Done. Thanks!
