### ISSUE TITLE
HTML content message

### ISSUE THREAD

**Issue by cope** [mathieudutour/Meteor-popup-confirm#3]
Would changing `<div>{{message}}</div>` to `<div>{{{message}}}</div>` allow for having html content messages?

**Comment by mathieudutour** [comment]
Hum possibly, I'm not using meteor anymore. Do you want to create a PR for this change?

**Comment by cope** [comment]
Sure.

**Comment by mathieudutour** [comment]
closed in https://github.com/mathieudutour/Meteor-popup-confirm/commit/b30786a4ef33081813fc3c7061ef31a51bf8c6b8
